<a href="https://colab.research.google.com/github/EdVKu/MeIA-2023/blob/main/Reto3_EduardoVazquezKuri.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

En primer lugar, se recabaron Los datos brutos de cada codón, a partir del archivo .csv

In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

codon = pd.read_csv('/content/codon_usage.csv', sep = '\t', header = 0)

Una Fila de números fue guardada dentro de Los nombres de columnas, por lo que se generó una lista de enteros del tamaño de las columnas del DataFrame. Finalmente, se fijaron Los nombres de las columnas usando esta lista.

In [ ]:
nombres = list(range(64))
codon.columns = nombres

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.000000,0.018349,0.000000,0.009174,0.064220,0.009174,0.018349,0.000000,0.000000,0.027523,...,0.009174,0.055046,0.027523,0.000000,0.027523,0.009174,0.009174,0.009174,0.000000,0.000000
1,0.002589,0.039148,0.031852,0.005480,0.000776,0.003668,0.000358,0.036549,0.060896,0.001604,...,0.025892,0.000445,0.000660,0.027529,0.000633,0.015795,0.015154,0.000140,0.000535,0.002378
2,0.001891,0.000630,0.000315,0.002206,0.025528,0.008824,0.010085,0.003152,0.001576,0.025528,...,0.010085,0.039395,0.025528,0.010715,0.050425,0.021116,0.014812,0.003467,0.000000,0.000315
3,0.001413,0.001413,0.000000,0.007063,0.012996,0.000989,0.004662,0.001695,0.000283,0.012007,...,0.006781,0.038000,0.017375,0.011301,0.055516,0.015398,0.005933,0.003673,0.000141,0.000141
4,0.022581,0.061290,0.024193,0.019355,0.001613,0.000000,0.004839,0.033871,0.019355,0.003226,...,0.014516,0.004839,0.004839,0.027419,0.006452,0.022581,0.012903,0.001613,0.000000,0.001613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4918,0.003566,0.023335,0.006949,0.018750,0.002336,0.001639,0.004912,0.010441,0.053597,0.011806,...,0.015272,0.023290,0.005338,0.024446,0.029277,0.027408,0.015216,0.001882,0.000306,0.000992
4919,0.000000,0.011976,0.005988,0.021956,0.009980,0.000000,0.003992,0.009980,0.003992,0.011976,...,0.021956,0.015968,0.000000,0.049900,0.025948,0.033932,0.019960,0.001996,0.000000,0.000000
4920,0.002162,0.002162,0.000432,0.009082,0.016434,0.001297,0.009082,0.001297,0.002595,0.010667,...,0.006919,0.045697,0.025083,0.007640,0.039066,0.020902,0.015136,0.001586,0.000000,0.000144
4921,0.004504,0.004504,0.002252,0.012669,0.012106,0.003097,0.009854,0.009009,0.003378,0.024493,...,0.007601,0.035191,0.013513,0.014358,0.035755,0.019707,0.005631,0.001689,0.001408,0.000563
4922,0.003755,0.023118,0.006968,0.018584,0.002525,0.001807,0.005222,0.010588,0.052403,0.011928,...,0.015535,0.023120,0.005467,0.024562,0.029182,0.027276,0.015073,0.001937,0.000334,0.001013